sonar.projectKey=Todo-Frontend
sonar.projectName=Todo Frontend
sonar.projectVersion=1.0

sonar.sources=src
sonar.sourceEncoding=UTF-8

# ignore folder không cần scan
sonar.exclusions=node_modules/**,.next/**,dist/**,coverage/**